[package]
name = "rust-competitive-journey"
authors = ["zook <me@nabilasykar.my.id>"]
version = "0.1.0"
edition = "2024"

[dependencies]
headless_chrome = "1.0.17"
list-modules = "0.1.6"
regex = "1.11.1"

[workspace]
members = ["hackerrank", "leetcode"]
